# Generated by Django 5.0.8 on 2025-11-08 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('proposal', 'Proposal Defense'), ('mid_defense', 'Mid Defense'), ('pre_defense', 'Pre Defense'), ('final_defense', 'Final Defense'), ('deadline', 'Submission Deadline'), ('meeting', 'Supervisor Meeting'), ('presentation', 'Presentation'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('other', 'Other')], max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('virtual_link', models.URLField(blank=True, help_text='Link for virtual meetings')),
                ('batch_year', models.IntegerField(blank=True, help_text='If event is for specific batch', null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('send_reminders', models.BooleanField(default=True)),
                ('reminder_hours_before', models.IntegerField(default=24, help_text='Hours before event to send reminder')),
                ('is_active', models.BooleanField(default=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='If event is for specific group', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='groups.group')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, help_text='Users invited to this event', related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('attended', 'Attended'), ('absent', 'Absent')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('rsvp_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event__start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reminder_sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('event_reminder', 'Event Reminder'), ('event_update', 'Event Update'), ('event_cancelled', 'Event Cancelled'), ('deadline_approaching', 'Deadline Approaching'), ('project_update', 'Project Update'), ('message', 'New Message'), ('forum_reply', 'Forum Reply'), ('system', 'System Notification'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link_url', models.CharField(blank=True, help_text='URL to redirect when clicked', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-delete after this date', null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.event')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('batch_year', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('proposal_deadline', models.DateField(blank=True, null=True)),
                ('mid_defense_start', models.DateField(blank=True, null=True)),
                ('mid_defense_end', models.DateField(blank=True, null=True)),
                ('pre_defense_start', models.DateField(blank=True, null=True)),
                ('pre_defense_end', models.DateField(blank=True, null=True)),
                ('final_defense_start', models.DateField(blank=True, null=True)),
                ('final_defense_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-batch_year'],
                'unique_together': {('name', 'batch_year')},
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_datetime', 'event_type'], name='events_even_start_d_30ecca_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['batch_year', 'is_active'], name='events_even_batch_y_84ad05_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['group', 'start_datetime'], name='events_even_group_i_e66a47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventattendance',
            unique_together={('event', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='eventreminder',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='events_noti_recipie_afc2f2_idx'),
        ),
    ]
