# Generated by Django 5.2.7 on 2025-11-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventsubmission_and_requirements'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventsubmission',
            new_name='events_even_event_i_84d543_idx',
            old_name='idx_event_student',
        ),
        migrations.RenameIndex(
            model_name='eventsubmission',
            new_name='events_even_status_15dfc5_idx',
            old_name='idx_status_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='late_submission_penalty',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_file_size_mb',
        ),
        migrations.RemoveField(
            model_name='event',
            name='requires_submission',
        ),
        migrations.RemoveField(
            model_name='event',
            name='submission_file_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='submission_instructions',
        ),
    ]
