# Generated by Django 5.0.8 on 2025-11-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_idx_event_student_events_even_event_i_84d543_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='late_submission_penalty',
            field=models.FloatField(default=10.0, help_text='Percentage penalty for late submissions'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_file_size_mb',
            field=models.IntegerField(default=10, help_text='Maximum file size in MB'),
        ),
        migrations.AddField(
            model_name='event',
            name='requires_submission',
            field=models.BooleanField(default=False, help_text='Does this event require file submission?'),
        ),
        migrations.AddField(
            model_name='event',
            name='submission_file_type',
            field=models.CharField(blank=True, help_text='Expected file type (e.g., PDF, DOCX, PPTX)', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='submission_instructions',
            field=models.TextField(blank=True, help_text='Instructions for students on what to submit'),
        ),
    ]
