# Generated by Django 5.0.8 on 2025-11-28 20:08

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student Project', 'verbose_name_plural': 'Student Projects'},
        ),
        migrations.AlterField(
            model_name='project',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='Progress percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['student', 'batch_year'], name='projects_pr_student_afadb7_idx'),
        ),
    ]
