# Generated by Django 5.0.8 on 2025-11-29 08:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Project Created'), ('submitted', 'Submitted for Review'), ('approved', 'Project Approved'), ('rejected', 'Project Rejected'), ('deliverable_submitted', 'Deliverable Submitted'), ('deliverable_approved', 'Deliverable Approved'), ('supervisor_assigned', 'Supervisor Assigned'), ('completed', 'Project Completed'), ('logsheet_submitted', 'Log Sheet Submitted'), ('logsheet_approved', 'Log Sheet Approved'), ('meeting_scheduled', 'Meeting Scheduled'), ('meeting_completed', 'Meeting Completed')], max_length=30),
        ),
        migrations.CreateModel(
            name='StudentProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('category', models.CharField(choices=[('progress', 'Progress Update'), ('concern', 'Concern/Issue'), ('achievement', 'Achievement'), ('reminder', 'Reminder'), ('other', 'Other')], default='progress', max_length=20)),
                ('is_visible_to_student', models.BooleanField(default=False, help_text='Make this note visible to student')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_notes', to='projects.project')),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supervisor Note',
                'verbose_name_plural': 'Supervisor Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('scheduled', 'Scheduled Meeting'), ('adhoc', 'Ad-hoc Discussion'), ('review', 'Progress Review'), ('defense', 'Defense/Presentation'), ('emergency', 'Emergency Meeting')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('meeting_link', models.URLField(blank=True)),
                ('agenda', models.TextField()),
                ('discussion_summary', models.TextField(blank=True)),
                ('action_items', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('student_attended', models.BooleanField(default=False)),
                ('supervisor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='projects.project')),
            ],
            options={
                'verbose_name': 'Supervisor Meeting',
                'verbose_name_plural': 'Supervisor Meetings',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tasks_completed', models.TextField(help_text='Tasks completed this week')),
                ('challenges_faced', models.TextField(blank=True, help_text='Challenges or blockers faced')),
                ('next_week_plan', models.TextField(help_text='Plan for next week')),
                ('hours_spent', models.DecimalField(decimal_places=1, help_text='Hours worked this week', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('attachment', models.FileField(blank=True, help_text='Optional progress screenshots/documents', null=True, upload_to='log_sheets/%Y/%m/')),
                ('supervisor_remarks', models.TextField(blank=True)),
                ('supervisor_rating', models.IntegerField(blank=True, help_text='1-5 rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_approved', models.BooleanField(default=False)),
                ('supervisor_signature', models.CharField(blank=True, help_text='Digital signature (supervisor name)', max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sheets', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Log Sheet',
                'verbose_name_plural': 'Project Log Sheets',
                'ordering': ['-week_number'],
                'unique_together': {('project', 'week_number')},
            },
        ),
    ]
