# Generated by Django 5.0.8 on 2025-12-25 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_late_submission_penalty_event_max_file_size_mb_and_more'),
        ('groups', '0003_alter_group_options_alter_groupmembership_options_and_more'),
        ('projects', '0005_group_meeting_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmeeting',
            options={'ordering': ['-scheduled_date']},
        ),
        migrations.RemoveField(
            model_name='groupmeeting',
            name='attended_students',
        ),
        migrations.AlterField(
            model_name='groupmeeting',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='groupmeeting',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_meeting', to='events.event'),
        ),
        migrations.AlterField(
            model_name='groupmeeting',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_meetings', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='groupmeeting',
            name='meeting_type',
            field=models.CharField(choices=[('weekly', 'Weekly Check-in'), ('progress_review', 'Progress Review'), ('defense_prep', 'Defense Preparation'), ('emergency', 'Emergency Meeting'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='groupmeeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Project Created'), ('submitted', 'Submitted for Review'), ('approved', 'Project Approved'), ('rejected', 'Project Rejected'), ('deliverable_submitted', 'Deliverable Submitted'), ('deliverable_approved', 'Deliverable Approved'), ('supervisor_assigned', 'Supervisor Assigned'), ('completed', 'Project Completed'), ('logsheet_submitted', 'Log Sheet Submitted'), ('logsheet_approved', 'Log Sheet Approved'), ('meeting_scheduled', 'Meeting Scheduled'), ('meeting_completed', 'Meeting Completed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='projectlogsheet',
            name='group_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_logsheets', to='projects.groupmeeting'),
        ),
    ]
