# Generated by Django 5.0.8 on 2025-11-07 19:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('active_users', models.IntegerField(default=0)),
                ('new_registrations', models.IntegerField(default=0)),
                ('user_retention_rate', models.FloatField(default=0)),
                ('total_projects', models.IntegerField(default=0)),
                ('projects_created', models.IntegerField(default=0)),
                ('projects_completed', models.IntegerField(default=0)),
                ('average_completion_time', models.FloatField(default=0)),
                ('resource_views', models.IntegerField(default=0)),
                ('resource_downloads', models.IntegerField(default=0)),
                ('forum_posts_created', models.IntegerField(default=0)),
                ('average_stress_level', models.FloatField(default=0)),
                ('system_uptime', models.FloatField(default=100.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'System analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProgressTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deliverables_completed', models.IntegerField(default=0)),
                ('total_deliverables', models.IntegerField(default=5)),
                ('meetings_attended', models.IntegerField(default=0)),
                ('milestones_reached', models.IntegerField(default=0)),
                ('code_commits', models.IntegerField(default=0)),
                ('documentation_pages', models.IntegerField(default=0)),
                ('supervisor_satisfaction', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('code_quality_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_history', to='projects.project')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project', 'timestamp'], name='analytics_p_project_c4ff28_idx')],
                'unique_together': {('project', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='StressLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('chat_sentiment_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
                ('deadline_pressure', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('workload_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('social_isolation_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('positive_messages', models.IntegerField(default=0)),
                ('negative_messages', models.IntegerField(default=0)),
                ('neutral_messages', models.IntegerField(default=0)),
                ('project_phase', models.CharField(blank=True, max_length=50)),
                ('week_of_semester', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stress_levels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['student', 'timestamp'], name='analytics_s_student_78cac4_idx'), models.Index(fields=['level'], name='analytics_s_level_0536da_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupervisorMeetingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('meeting_type', models.CharField(choices=[('initial', 'Initial Meeting'), ('progress', 'Progress Review'), ('technical', 'Technical Discussion'), ('feedback', 'Feedback Session'), ('final', 'Final Review'), ('emergency', 'Emergency Meeting')], max_length=50)),
                ('location', models.CharField(blank=True, default='Virtual', max_length=100)),
                ('topics_discussed', models.TextField()),
                ('action_items', models.TextField(blank=True)),
                ('decisions_made', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('student_preparation_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('meeting_effectiveness_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_by_supervisor', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='projects.project')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_meetings', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-meeting_date'],
                'indexes': [models.Index(fields=['student', 'meeting_date'], name='analytics_s_student_65ff63_idx'), models.Index(fields=['supervisor', 'meeting_date'], name='analytics_s_supervi_d97558_idx'), models.Index(fields=['project', 'meeting_date'], name='analytics_s_project_d58109_idx')],
            },
        ),
    ]
