# Generated by Django 5.2.7 on 2025-11-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_supervisorfeedback_logsheet'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supervisorfeedback',
            new_name='analytics_s_student_3ef0fb_idx',
            old_name='idx_student_date',
        ),
        migrations.RenameIndex(
            model_name='supervisorfeedback',
            new_name='analytics_s_supervi_b69526_idx',
            old_name='idx_supervisor_date',
        ),
        migrations.RenameIndex(
            model_name='supervisorfeedback',
            new_name='analytics_s_project_a8bc54_idx',
            old_name='idx_project',
        ),
        migrations.RemoveField(
            model_name='supervisormeetinglog',
            name='affects_progress',
        ),
        migrations.RemoveField(
            model_name='supervisormeetinglog',
            name='affects_stress',
        ),
        migrations.RemoveField(
            model_name='supervisormeetinglog',
            name='feedback_provided',
        ),
    ]
