# Generated by Django 5.0.8 on 2025-11-28 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_rename_idx_student_date_analytics_s_student_3ef0fb_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stresslevel',
            options={'ordering': ['-calculated_at']},
        ),
        migrations.RemoveIndex(
            model_name='stresslevel',
            name='analytics_s_student_78cac4_idx',
        ),
        migrations.RenameField(
            model_name='stresslevel',
            old_name='timestamp',
            new_name='calculated_at',
        ),
        migrations.AlterField(
            model_name='stresslevel',
            name='chat_sentiment_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stresslevel',
            name='deadline_pressure',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stresslevel',
            name='social_isolation_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stresslevel',
            name='workload_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddIndex(
            model_name='stresslevel',
            index=models.Index(fields=['student', 'calculated_at'], name='analytics_s_student_d539e5_idx'),
        ),
    ]
