# Generated by Django 5.0.8 on 2025-11-29 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_stresslevel_options_and_more'),
        ('projects', '0003_alter_projectactivity_action_studentprogressnote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisormeetinglog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_logs', to='projects.project'),
        ),
    ]
