# Generated by Django 5.0.8 on 2025-11-29 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_supervisormeetinglog_project'),
        ('projects', '0003_alter_projectactivity_action_studentprogressnote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('stress_analysis', 'Stress Analysis'), ('feedback_added', 'Feedback Added'), ('meeting_logged', 'Meeting Logged'), ('project_created', 'Project Created'), ('deliverable_submitted', 'Deliverable Submitted'), ('deliverable_approved', 'Deliverable Approved'), ('user_created', 'User Created'), ('user_login', 'User Login'), ('group_created', 'Group Created'), ('system_event', 'System Event'), ('analytics_run', 'Analytics Run')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'System Activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['activity_type', 'timestamp'], name='analytics_s_activit_c18fc8_idx'), models.Index(fields=['timestamp'], name='analytics_s_timesta_4c0bbb_idx'), models.Index(fields=['user', 'timestamp'], name='analytics_s_user_id_d14f64_idx')],
            },
        ),
    ]
