# Generated by Django 5.0.8 on 2025-11-29 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('projects', '0002_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to='projects.project'),
        ),
    ]
