# Generated by Django 5.0.8 on 2025-12-24 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forumpost_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumreply',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='forum.forumreply'),
        ),
    ]
