# Generated by Django 5.0.8 on 2025-12-23 14:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='pending_chat_attachments/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending Delivery'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('sentiment_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_delivery_time', models.DateTimeField(blank=True, help_text='When this message should be delivered', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Message expires if not delivered by this time', null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('delivered_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_origin', to='chat.message')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_replies', to='chat.message')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_messages', to='chat.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_pending_messages', to=settings.AUTH_USER_MODEL)),
                ('target_supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='pending_messages_to_receive', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_delivery_time'], name='chat_pendin_status_36b499_idx'), models.Index(fields=['target_supervisor', 'status'], name='chat_pendin_target__358fc5_idx'), models.Index(fields=['sender', 'status'], name='chat_pendin_sender__92b132_idx')],
            },
        ),
    ]
