# Generated by Django 5.0.8 on 2025-08-23 17:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_users', models.IntegerField(default=0)),
                ('pending_users', models.IntegerField(default=0)),
                ('pending_projects', models.IntegerField(default=0)),
                ('project_progress', models.FloatField(default=0.0)),
                ('stress_level', models.FloatField(default=0.0)),
                ('active_groups', models.IntegerField(default=0)),
                ('students_supervised', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
