# Generated by Django 5.0.8 on 2025-12-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_universitydatabase_user_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='schedule_days',
            field=models.CharField(blank=True, help_text='Comma-separated days: Mon,Tue,Wed,Thu,Fri,Sat,Sun', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='schedule_enabled',
            field=models.BooleanField(default=False, help_text='Enable/disable time restrictions for this supervisor'),
        ),
        migrations.AddField(
            model_name='user',
            name='schedule_end_time',
            field=models.TimeField(blank=True, help_text='Time when students must stop messaging (e.g., 05:00 PM)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='schedule_start_time',
            field=models.TimeField(blank=True, help_text='Time when students can start messaging (e.g., 09:00 AM)', null=True),
        ),
    ]
