# Generated by Django 5.0.8 on 2025-12-24 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('supervisor', 'batch_year'), name='unique_active_supervisor_per_batch'),
        ),
    ]
