# Generated by Django 5.0.8 on 2025-12-24 19:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_unique_active_supervisor_per_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='groupmembership',
            options={'ordering': ['joined_at']},
        ),
        migrations.RemoveConstraint(
            model_name='group',
            name='unique_active_supervisor_per_batch',
        ),
        migrations.RemoveField(
            model_name='group',
            name='is_full',
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='max_students',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='group',
            name='min_students',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='groupactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Group Created'), ('updated', 'Group Updated'), ('student_added', 'Student Added'), ('student_removed', 'Student Removed'), ('supervisor_changed', 'Supervisor Changed'), ('group_started', 'Group Started'), ('group_completed', 'Group Completed')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['supervisor', 'is_active'], name='groups_grou_supervi_b135ee_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['batch_year'], name='groups_grou_batch_y_ce2043_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['student', 'is_active'], name='groups_grou_student_0a0f06_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'is_active'], name='groups_grou_group_i_f7e3a8_idx'),
        ),
    ]
