# Generated by Django 5.0.8 on 2025-11-29 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_likes', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource Like',
                'verbose_name_plural': 'Resource Likes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource', 'user'], name='resources_r_resourc_aa2d97_idx'), models.Index(fields=['created_at'], name='resources_r_created_478025_idx')],
                'unique_together': {('resource', 'user')},
            },
        ),
    ]
